---
# Creating a namespace called minecraft.
kind: Namespace
apiVersion: v1
metadata:
  name: minecraft

---
# Creating a storage class for the persistent volume claim.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-disk
  namespace: minecraft
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd

---
# Creating a persistent volume claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mc-bedrock
  namespace: minecraft
spec:
  storageClassName: fast-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Creating a deployment for the Minecraft Bedrock server.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-bedrock
  namespace: minecraft
  labels:
    app: mc-bedrock
spec:
  replicas: 1
  template:
    metadata:
      name: mc-bedrock
      labels:
        app: mc-bedrock
    spec:
      containers:
        - name: mc-bedrock
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: adventure
            - name: DIFFICULTY
              value: normal
            - name: WHITE_LIST
              value: "true"
            - name: ONLINE_MODE
              value: "true"
            - name: ALLOW_CHEATS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mc-bedrock
  selector:
    matchLabels:
      app: mc-bedrock

---
# Creating a service for the Minecraft Bedrock server.
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock
  namespace: minecraft
  labels:
    app: mc-bedrock
spec:
  selector:
    app: mc-bedrock
  ports:
    - port: 19132
      protocol: UDP
  type: LoadBalancer
